# Generated by Django 4.2.1 on 2023-06-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapsiya', '0005_alter_admin_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
